/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedGuideRouteImport } from './routes/_authenticated/guide'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAdminIntelligenceRouteImport } from './routes/_authenticated/admin/intelligence'
import { Route as ApiPublicQuotesRouteImport } from './routes/api/public/quotes'
import { Route as ApiPublicAgentRegisterRouteImport } from './routes/api/public/agent/register'
import { Route as ApiPublicCronCommissionReadinessRouteImport } from './routes/api/public/cron/commission-readiness'
import { Route as ApiPublicCronIngestNewsRouteImport } from './routes/api/public/cron/ingest-news'
import { Route as ApiPublicCronInstrumentReadinessRouteImport } from './routes/api/public/cron/instrument-readiness'
import { Route as ApiPublicCronPurgeAccountsRouteImport } from './routes/api/public/cron/purge-accounts'
import { Route as ApiPublicCronRefreshSpecsRouteImport } from './routes/api/public/cron/refresh-specs'
import { Route as ApiPublicCronSampleSpreadsRouteImport } from './routes/api/public/cron/sample-spreads'
import { Route as ApiPublicCronScanRouteImport } from './routes/api/public/cron/scan'
import { Route as ApiPublicCronShadowResolveRouteImport } from './routes/api/public/cron/shadow-resolve'
import { Route as ApiPublicCronTelemetryRollupRouteImport } from './routes/api/public/cron/telemetry-rollup'
import { Route as ApiPublicCronVerifyRemindersRouteImport } from './routes/api/public/cron/verify-reminders'
import { Route as ApiPublicCronWeeklyReportRouteImport } from './routes/api/public/cron/weekly-report'
import { Route as ApiPublicWorkerDispatchRouteImport } from './routes/api/public/worker/dispatch'
import { Route as ApiPublicWorkerProcessRouteImport } from './routes/api/public/worker/process'
import { Route as ApiPublicWorkerReconcileRouteImport } from './routes/api/public/worker/reconcile'
import { Route as ApiPublicWorkerReconcileActiveRouteImport } from './routes/api/public/worker/reconcile-active'
import { Route as ApiPublicWorkerShadowRouteImport } from './routes/api/public/worker/shadow'
import { Route as ApiPublicWorkerTelemetryRouteImport } from './routes/api/public/worker/telemetry'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuideRoute = AuthenticatedGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminIntelligenceRoute =
  AuthenticatedAdminIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicQuotesRoute = ApiPublicQuotesRouteImport.update({
  id: '/api/public/quotes',
  path: '/api/public/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentRegisterRoute = ApiPublicAgentRegisterRouteImport.update({
  id: '/api/public/agent/register',
  path: '/api/public/agent/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronCommissionReadinessRoute =
  ApiPublicCronCommissionReadinessRouteImport.update({
    id: '/api/public/cron/commission-readiness',
    path: '/api/public/cron/commission-readiness',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronIngestNewsRoute = ApiPublicCronIngestNewsRouteImport.update({
  id: '/api/public/cron/ingest-news',
  path: '/api/public/cron/ingest-news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronInstrumentReadinessRoute =
  ApiPublicCronInstrumentReadinessRouteImport.update({
    id: '/api/public/cron/instrument-readiness',
    path: '/api/public/cron/instrument-readiness',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronPurgeAccountsRoute =
  ApiPublicCronPurgeAccountsRouteImport.update({
    id: '/api/public/cron/purge-accounts',
    path: '/api/public/cron/purge-accounts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronRefreshSpecsRoute =
  ApiPublicCronRefreshSpecsRouteImport.update({
    id: '/api/public/cron/refresh-specs',
    path: '/api/public/cron/refresh-specs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronSampleSpreadsRoute =
  ApiPublicCronSampleSpreadsRouteImport.update({
    id: '/api/public/cron/sample-spreads',
    path: '/api/public/cron/sample-spreads',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronScanRoute = ApiPublicCronScanRouteImport.update({
  id: '/api/public/cron/scan',
  path: '/api/public/cron/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronShadowResolveRoute =
  ApiPublicCronShadowResolveRouteImport.update({
    id: '/api/public/cron/shadow-resolve',
    path: '/api/public/cron/shadow-resolve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronTelemetryRollupRoute =
  ApiPublicCronTelemetryRollupRouteImport.update({
    id: '/api/public/cron/telemetry-rollup',
    path: '/api/public/cron/telemetry-rollup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronVerifyRemindersRoute =
  ApiPublicCronVerifyRemindersRouteImport.update({
    id: '/api/public/cron/verify-reminders',
    path: '/api/public/cron/verify-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronWeeklyReportRoute =
  ApiPublicCronWeeklyReportRouteImport.update({
    id: '/api/public/cron/weekly-report',
    path: '/api/public/cron/weekly-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkerDispatchRoute = ApiPublicWorkerDispatchRouteImport.update({
  id: '/api/public/worker/dispatch',
  path: '/api/public/worker/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerProcessRoute = ApiPublicWorkerProcessRouteImport.update({
  id: '/api/public/worker/process',
  path: '/api/public/worker/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerReconcileRoute =
  ApiPublicWorkerReconcileRouteImport.update({
    id: '/api/public/worker/reconcile',
    path: '/api/public/worker/reconcile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkerReconcileActiveRoute =
  ApiPublicWorkerReconcileActiveRouteImport.update({
    id: '/api/public/worker/reconcile-active',
    path: '/api/public/worker/reconcile-active',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkerShadowRoute = ApiPublicWorkerShadowRouteImport.update({
  id: '/api/public/worker/shadow',
  path: '/api/public/worker/shadow',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerTelemetryRoute =
  ApiPublicWorkerTelemetryRouteImport.update({
    id: '/api/public/worker/telemetry',
    path: '/api/public/worker/telemetry',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/guide': typeof AuthenticatedGuideRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/intelligence': typeof AuthenticatedAdminIntelligenceRoute
  '/api/public/quotes': typeof ApiPublicQuotesRoute
  '/api/public/agent/register': typeof ApiPublicAgentRegisterRoute
  '/api/public/cron/commission-readiness': typeof ApiPublicCronCommissionReadinessRoute
  '/api/public/cron/ingest-news': typeof ApiPublicCronIngestNewsRoute
  '/api/public/cron/instrument-readiness': typeof ApiPublicCronInstrumentReadinessRoute
  '/api/public/cron/purge-accounts': typeof ApiPublicCronPurgeAccountsRoute
  '/api/public/cron/refresh-specs': typeof ApiPublicCronRefreshSpecsRoute
  '/api/public/cron/sample-spreads': typeof ApiPublicCronSampleSpreadsRoute
  '/api/public/cron/scan': typeof ApiPublicCronScanRoute
  '/api/public/cron/shadow-resolve': typeof ApiPublicCronShadowResolveRoute
  '/api/public/cron/telemetry-rollup': typeof ApiPublicCronTelemetryRollupRoute
  '/api/public/cron/verify-reminders': typeof ApiPublicCronVerifyRemindersRoute
  '/api/public/cron/weekly-report': typeof ApiPublicCronWeeklyReportRoute
  '/api/public/worker/dispatch': typeof ApiPublicWorkerDispatchRoute
  '/api/public/worker/process': typeof ApiPublicWorkerProcessRoute
  '/api/public/worker/reconcile': typeof ApiPublicWorkerReconcileRoute
  '/api/public/worker/reconcile-active': typeof ApiPublicWorkerReconcileActiveRoute
  '/api/public/worker/shadow': typeof ApiPublicWorkerShadowRoute
  '/api/public/worker/telemetry': typeof ApiPublicWorkerTelemetryRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/guide': typeof AuthenticatedGuideRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/intelligence': typeof AuthenticatedAdminIntelligenceRoute
  '/api/public/quotes': typeof ApiPublicQuotesRoute
  '/api/public/agent/register': typeof ApiPublicAgentRegisterRoute
  '/api/public/cron/commission-readiness': typeof ApiPublicCronCommissionReadinessRoute
  '/api/public/cron/ingest-news': typeof ApiPublicCronIngestNewsRoute
  '/api/public/cron/instrument-readiness': typeof ApiPublicCronInstrumentReadinessRoute
  '/api/public/cron/purge-accounts': typeof ApiPublicCronPurgeAccountsRoute
  '/api/public/cron/refresh-specs': typeof ApiPublicCronRefreshSpecsRoute
  '/api/public/cron/sample-spreads': typeof ApiPublicCronSampleSpreadsRoute
  '/api/public/cron/scan': typeof ApiPublicCronScanRoute
  '/api/public/cron/shadow-resolve': typeof ApiPublicCronShadowResolveRoute
  '/api/public/cron/telemetry-rollup': typeof ApiPublicCronTelemetryRollupRoute
  '/api/public/cron/verify-reminders': typeof ApiPublicCronVerifyRemindersRoute
  '/api/public/cron/weekly-report': typeof ApiPublicCronWeeklyReportRoute
  '/api/public/worker/dispatch': typeof ApiPublicWorkerDispatchRoute
  '/api/public/worker/process': typeof ApiPublicWorkerProcessRoute
  '/api/public/worker/reconcile': typeof ApiPublicWorkerReconcileRoute
  '/api/public/worker/reconcile-active': typeof ApiPublicWorkerReconcileActiveRoute
  '/api/public/worker/shadow': typeof ApiPublicWorkerShadowRoute
  '/api/public/worker/telemetry': typeof ApiPublicWorkerTelemetryRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/guide': typeof AuthenticatedGuideRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/intelligence': typeof AuthenticatedAdminIntelligenceRoute
  '/api/public/quotes': typeof ApiPublicQuotesRoute
  '/api/public/agent/register': typeof ApiPublicAgentRegisterRoute
  '/api/public/cron/commission-readiness': typeof ApiPublicCronCommissionReadinessRoute
  '/api/public/cron/ingest-news': typeof ApiPublicCronIngestNewsRoute
  '/api/public/cron/instrument-readiness': typeof ApiPublicCronInstrumentReadinessRoute
  '/api/public/cron/purge-accounts': typeof ApiPublicCronPurgeAccountsRoute
  '/api/public/cron/refresh-specs': typeof ApiPublicCronRefreshSpecsRoute
  '/api/public/cron/sample-spreads': typeof ApiPublicCronSampleSpreadsRoute
  '/api/public/cron/scan': typeof ApiPublicCronScanRoute
  '/api/public/cron/shadow-resolve': typeof ApiPublicCronShadowResolveRoute
  '/api/public/cron/telemetry-rollup': typeof ApiPublicCronTelemetryRollupRoute
  '/api/public/cron/verify-reminders': typeof ApiPublicCronVerifyRemindersRoute
  '/api/public/cron/weekly-report': typeof ApiPublicCronWeeklyReportRoute
  '/api/public/worker/dispatch': typeof ApiPublicWorkerDispatchRoute
  '/api/public/worker/process': typeof ApiPublicWorkerProcessRoute
  '/api/public/worker/reconcile': typeof ApiPublicWorkerReconcileRoute
  '/api/public/worker/reconcile-active': typeof ApiPublicWorkerReconcileActiveRoute
  '/api/public/worker/shadow': typeof ApiPublicWorkerShadowRoute
  '/api/public/worker/telemetry': typeof ApiPublicWorkerTelemetryRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/connect'
    | '/mcp'
    | '/sitemap.xml'
    | '/admin'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/accounts'
    | '/feed'
    | '/guide'
    | '/history'
    | '/performance'
    | '/settings'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/intelligence'
    | '/api/public/quotes'
    | '/api/public/agent/register'
    | '/api/public/cron/commission-readiness'
    | '/api/public/cron/ingest-news'
    | '/api/public/cron/instrument-readiness'
    | '/api/public/cron/purge-accounts'
    | '/api/public/cron/refresh-specs'
    | '/api/public/cron/sample-spreads'
    | '/api/public/cron/scan'
    | '/api/public/cron/shadow-resolve'
    | '/api/public/cron/telemetry-rollup'
    | '/api/public/cron/verify-reminders'
    | '/api/public/cron/weekly-report'
    | '/api/public/worker/dispatch'
    | '/api/public/worker/process'
    | '/api/public/worker/reconcile'
    | '/api/public/worker/reconcile-active'
    | '/api/public/worker/shadow'
    | '/api/public/worker/telemetry'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/connect'
    | '/mcp'
    | '/sitemap.xml'
    | '/admin'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/accounts'
    | '/feed'
    | '/guide'
    | '/history'
    | '/performance'
    | '/settings'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/intelligence'
    | '/api/public/quotes'
    | '/api/public/agent/register'
    | '/api/public/cron/commission-readiness'
    | '/api/public/cron/ingest-news'
    | '/api/public/cron/instrument-readiness'
    | '/api/public/cron/purge-accounts'
    | '/api/public/cron/refresh-specs'
    | '/api/public/cron/sample-spreads'
    | '/api/public/cron/scan'
    | '/api/public/cron/shadow-resolve'
    | '/api/public/cron/telemetry-rollup'
    | '/api/public/cron/verify-reminders'
    | '/api/public/cron/weekly-report'
    | '/api/public/worker/dispatch'
    | '/api/public/worker/process'
    | '/api/public/worker/reconcile'
    | '/api/public/worker/reconcile-active'
    | '/api/public/worker/shadow'
    | '/api/public/worker/telemetry'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/connect'
    | '/mcp'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/accounts'
    | '/_authenticated/feed'
    | '/_authenticated/guide'
    | '/_authenticated/history'
    | '/_authenticated/performance'
    | '/_authenticated/settings'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/intelligence'
    | '/api/public/quotes'
    | '/api/public/agent/register'
    | '/api/public/cron/commission-readiness'
    | '/api/public/cron/ingest-news'
    | '/api/public/cron/instrument-readiness'
    | '/api/public/cron/purge-accounts'
    | '/api/public/cron/refresh-specs'
    | '/api/public/cron/sample-spreads'
    | '/api/public/cron/scan'
    | '/api/public/cron/shadow-resolve'
    | '/api/public/cron/telemetry-rollup'
    | '/api/public/cron/verify-reminders'
    | '/api/public/cron/weekly-report'
    | '/api/public/worker/dispatch'
    | '/api/public/worker/process'
    | '/api/public/worker/reconcile'
    | '/api/public/worker/reconcile-active'
    | '/api/public/worker/shadow'
    | '/api/public/worker/telemetry'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConnectRoute: typeof ConnectRoute
  McpRoute: typeof McpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicQuotesRoute: typeof ApiPublicQuotesRoute
  ApiPublicAgentRegisterRoute: typeof ApiPublicAgentRegisterRoute
  ApiPublicCronCommissionReadinessRoute: typeof ApiPublicCronCommissionReadinessRoute
  ApiPublicCronIngestNewsRoute: typeof ApiPublicCronIngestNewsRoute
  ApiPublicCronInstrumentReadinessRoute: typeof ApiPublicCronInstrumentReadinessRoute
  ApiPublicCronPurgeAccountsRoute: typeof ApiPublicCronPurgeAccountsRoute
  ApiPublicCronRefreshSpecsRoute: typeof ApiPublicCronRefreshSpecsRoute
  ApiPublicCronSampleSpreadsRoute: typeof ApiPublicCronSampleSpreadsRoute
  ApiPublicCronScanRoute: typeof ApiPublicCronScanRoute
  ApiPublicCronShadowResolveRoute: typeof ApiPublicCronShadowResolveRoute
  ApiPublicCronTelemetryRollupRoute: typeof ApiPublicCronTelemetryRollupRoute
  ApiPublicCronVerifyRemindersRoute: typeof ApiPublicCronVerifyRemindersRoute
  ApiPublicCronWeeklyReportRoute: typeof ApiPublicCronWeeklyReportRoute
  ApiPublicWorkerDispatchRoute: typeof ApiPublicWorkerDispatchRoute
  ApiPublicWorkerProcessRoute: typeof ApiPublicWorkerProcessRoute
  ApiPublicWorkerReconcileRoute: typeof ApiPublicWorkerReconcileRoute
  ApiPublicWorkerReconcileActiveRoute: typeof ApiPublicWorkerReconcileActiveRoute
  ApiPublicWorkerShadowRoute: typeof ApiPublicWorkerShadowRoute
  ApiPublicWorkerTelemetryRoute: typeof ApiPublicWorkerTelemetryRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guide': {
      id: '/_authenticated/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof AuthenticatedGuideRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/intelligence': {
      id: '/_authenticated/admin/intelligence'
      path: '/intelligence'
      fullPath: '/admin/intelligence'
      preLoaderRoute: typeof AuthenticatedAdminIntelligenceRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/quotes': {
      id: '/api/public/quotes'
      path: '/api/public/quotes'
      fullPath: '/api/public/quotes'
      preLoaderRoute: typeof ApiPublicQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/register': {
      id: '/api/public/agent/register'
      path: '/api/public/agent/register'
      fullPath: '/api/public/agent/register'
      preLoaderRoute: typeof ApiPublicAgentRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/commission-readiness': {
      id: '/api/public/cron/commission-readiness'
      path: '/api/public/cron/commission-readiness'
      fullPath: '/api/public/cron/commission-readiness'
      preLoaderRoute: typeof ApiPublicCronCommissionReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/ingest-news': {
      id: '/api/public/cron/ingest-news'
      path: '/api/public/cron/ingest-news'
      fullPath: '/api/public/cron/ingest-news'
      preLoaderRoute: typeof ApiPublicCronIngestNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/instrument-readiness': {
      id: '/api/public/cron/instrument-readiness'
      path: '/api/public/cron/instrument-readiness'
      fullPath: '/api/public/cron/instrument-readiness'
      preLoaderRoute: typeof ApiPublicCronInstrumentReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/purge-accounts': {
      id: '/api/public/cron/purge-accounts'
      path: '/api/public/cron/purge-accounts'
      fullPath: '/api/public/cron/purge-accounts'
      preLoaderRoute: typeof ApiPublicCronPurgeAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/refresh-specs': {
      id: '/api/public/cron/refresh-specs'
      path: '/api/public/cron/refresh-specs'
      fullPath: '/api/public/cron/refresh-specs'
      preLoaderRoute: typeof ApiPublicCronRefreshSpecsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/sample-spreads': {
      id: '/api/public/cron/sample-spreads'
      path: '/api/public/cron/sample-spreads'
      fullPath: '/api/public/cron/sample-spreads'
      preLoaderRoute: typeof ApiPublicCronSampleSpreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/scan': {
      id: '/api/public/cron/scan'
      path: '/api/public/cron/scan'
      fullPath: '/api/public/cron/scan'
      preLoaderRoute: typeof ApiPublicCronScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/shadow-resolve': {
      id: '/api/public/cron/shadow-resolve'
      path: '/api/public/cron/shadow-resolve'
      fullPath: '/api/public/cron/shadow-resolve'
      preLoaderRoute: typeof ApiPublicCronShadowResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/telemetry-rollup': {
      id: '/api/public/cron/telemetry-rollup'
      path: '/api/public/cron/telemetry-rollup'
      fullPath: '/api/public/cron/telemetry-rollup'
      preLoaderRoute: typeof ApiPublicCronTelemetryRollupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/verify-reminders': {
      id: '/api/public/cron/verify-reminders'
      path: '/api/public/cron/verify-reminders'
      fullPath: '/api/public/cron/verify-reminders'
      preLoaderRoute: typeof ApiPublicCronVerifyRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/weekly-report': {
      id: '/api/public/cron/weekly-report'
      path: '/api/public/cron/weekly-report'
      fullPath: '/api/public/cron/weekly-report'
      preLoaderRoute: typeof ApiPublicCronWeeklyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/dispatch': {
      id: '/api/public/worker/dispatch'
      path: '/api/public/worker/dispatch'
      fullPath: '/api/public/worker/dispatch'
      preLoaderRoute: typeof ApiPublicWorkerDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/process': {
      id: '/api/public/worker/process'
      path: '/api/public/worker/process'
      fullPath: '/api/public/worker/process'
      preLoaderRoute: typeof ApiPublicWorkerProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/reconcile': {
      id: '/api/public/worker/reconcile'
      path: '/api/public/worker/reconcile'
      fullPath: '/api/public/worker/reconcile'
      preLoaderRoute: typeof ApiPublicWorkerReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/reconcile-active': {
      id: '/api/public/worker/reconcile-active'
      path: '/api/public/worker/reconcile-active'
      fullPath: '/api/public/worker/reconcile-active'
      preLoaderRoute: typeof ApiPublicWorkerReconcileActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/shadow': {
      id: '/api/public/worker/shadow'
      path: '/api/public/worker/shadow'
      fullPath: '/api/public/worker/shadow'
      preLoaderRoute: typeof ApiPublicWorkerShadowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/telemetry': {
      id: '/api/public/worker/telemetry'
      path: '/api/public/worker/telemetry'
      fullPath: '/api/public/worker/telemetry'
      preLoaderRoute: typeof ApiPublicWorkerTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIntelligenceRoute: typeof AuthenticatedAdminIntelligenceRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIntelligenceRoute: AuthenticatedAdminIntelligenceRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedGuideRoute: typeof AuthenticatedGuideRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedGuideRoute: AuthenticatedGuideRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConnectRoute: ConnectRoute,
  McpRoute: McpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicQuotesRoute: ApiPublicQuotesRoute,
  ApiPublicAgentRegisterRoute: ApiPublicAgentRegisterRoute,
  ApiPublicCronCommissionReadinessRoute: ApiPublicCronCommissionReadinessRoute,
  ApiPublicCronIngestNewsRoute: ApiPublicCronIngestNewsRoute,
  ApiPublicCronInstrumentReadinessRoute: ApiPublicCronInstrumentReadinessRoute,
  ApiPublicCronPurgeAccountsRoute: ApiPublicCronPurgeAccountsRoute,
  ApiPublicCronRefreshSpecsRoute: ApiPublicCronRefreshSpecsRoute,
  ApiPublicCronSampleSpreadsRoute: ApiPublicCronSampleSpreadsRoute,
  ApiPublicCronScanRoute: ApiPublicCronScanRoute,
  ApiPublicCronShadowResolveRoute: ApiPublicCronShadowResolveRoute,
  ApiPublicCronTelemetryRollupRoute: ApiPublicCronTelemetryRollupRoute,
  ApiPublicCronVerifyRemindersRoute: ApiPublicCronVerifyRemindersRoute,
  ApiPublicCronWeeklyReportRoute: ApiPublicCronWeeklyReportRoute,
  ApiPublicWorkerDispatchRoute: ApiPublicWorkerDispatchRoute,
  ApiPublicWorkerProcessRoute: ApiPublicWorkerProcessRoute,
  ApiPublicWorkerReconcileRoute: ApiPublicWorkerReconcileRoute,
  ApiPublicWorkerReconcileActiveRoute: ApiPublicWorkerReconcileActiveRoute,
  ApiPublicWorkerShadowRoute: ApiPublicWorkerShadowRoute,
  ApiPublicWorkerTelemetryRoute: ApiPublicWorkerTelemetryRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
